FROM eclipse-temurin:17

WORKDIR /app

COPY target/springboot-connectmate-rest-api-0.0.1-SNAPSHOT.jar /app/springboot-connectmate-rest-api.jar

ENTRYPOINT ["java", "-jar", "springboot-connectmate-rest-api.jar"]
