version: "3.8"

services:
  springboot-app:
    container_name: springboot-app
    image: springboot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: connectmate
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: connectmate
      MYSQL_ROOT_PASSWORD: root
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net:
